services:
  api:
    build: .
    ports:
      - 8000:8000
    environment:
      - MONGO_URI=mongodb://mongo_db:27017
      - ELASTICSEARCH_URI=http://elasticsearch_db:9200
    depends_on:
      - mongo_db
      - elasticsearch_db

  mongo_db:
    image: mongo:7.0.2
    volumes:
      - ./data/mongo:/data/db

  elasticsearch_db:
    image: elasticsearch:8.10.2
    healthcheck:
      test: curl -s http://elasticsearch_db:9200 >/dev/null || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data