services:
  api_node_01:
    build: .
    environment:
      - MONGO_URI=mongodb://mongo_db:27017
      - ELASTICSEARCH_URI=http://elasticsearch_db:9200
      - MEMCACHED_URI=memcached_node_01:11211,memcached_node_02:11211,memcached_node_03:11211
    depends_on:
      elasticsearch_db:
        condition: service_healthy
      mongo_db:
        condition: service_started

  api_node_02:
    build: .
    environment:
      - MONGO_URI=mongodb://mongo_db:27017
      - ELASTICSEARCH_URI=http://elasticsearch_db:9200
      - MEMCACHED_URI=memcached_node_01:11211,memcached_node_02:11211,memcached_node_03:11211
    depends_on:
      elasticsearch_db:
        condition: service_healthy
      mongo_db:
        condition: service_started

  api_node_03:
    build: .
    environment:
      - MONGO_URI=mongodb://mongo_db:27017
      - ELASTICSEARCH_URI=http://elasticsearch_db:9200
      - MEMCACHED_URI=memcached_node_01:11211,memcached_node_02:11211,memcached_node_03:11211
    depends_on:
      elasticsearch_db:
        condition: service_healthy
      mongo_db:
        condition: service_started

  mongo_db:
    image: mongo:7.0.2
    volumes:
      - ./data/mongo:/data/db

  elasticsearch_db:
    image: elasticsearch:8.10.2
    healthcheck:
      interval: 5s
      retries: 80
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://elasticsearch_db:9200
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data

  memcached_node_01:
    image: memcached

  memcached_node_02:
    image: memcached

  memcached_node_03:
    image: memcached

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api_node_01
      - api_node_02
      - api_node_03