services:
  api_node_01:
    build: .
    env_file:
      - docker.env
    depends_on:
      elasticsearch_node_01:
        condition: service_healthy
      elasticsearch_node_02:
        condition: service_healthy
      elasticsearch_node_03:
        condition: service_healthy
      mongo_db:
        condition: service_started

  api_node_02:
    build: .
    env_file:
      - docker.env
    depends_on:
      elasticsearch_node_01:
        condition: service_healthy
      elasticsearch_node_02:
        condition: service_healthy
      elasticsearch_node_03:
        condition: service_healthy
      mongo_db:
        condition: service_started

  api_node_03:
    build: .
    env_file:
      - docker.env
    depends_on:
      elasticsearch_node_01:
        condition: service_healthy
      elasticsearch_node_02:
        condition: service_healthy
      elasticsearch_node_03:
        condition: service_healthy
      mongo_db:
        condition: service_started

  mongo_db:
    image: mongo:7.0.2
    volumes:
      - ./data/mongo:/data/db

  elasticsearch_node_01:
    image: elasticsearch:8.10.2
    healthcheck:
      interval: 5s
      retries: 80
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://elasticsearch_db:9200
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - cluster.name=es_cluster
      - node.max_local_storage_nodes=3
    volumes:
      - ./data/elasticsearch_01:/usr/share/elasticsearch/data

  elasticsearch_node_02:
    image: elasticsearch:8.10.2
    healthcheck:
      interval: 5s
      retries: 80
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://elasticsearch_db:9200
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - cluster.name=es_cluster
      - node.max_local_storage_nodes=3
      - discovery.zen.ping.unicast.hosts=elasticsearch_node_01
    volumes:
      - ./data/elasticsearch_02:/usr/share/elasticsearch/data

  elasticsearch_node_03:
    image: elasticsearch:8.10.2
    healthcheck:
      interval: 5s
      retries: 80
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://elasticsearch_db:9200
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - cluster.name=es_cluster
      - node.max_local_storage_nodes=3
      - discovery.zen.ping.unicast.hosts=elasticsearch_node_01
    volumes:
      - ./data/elasticsearch_03:/usr/share/elasticsearch/data

  memcached_node_01:
    image: memcached

  memcached_node_02:
    image: memcached

  memcached_node_03:
    image: memcached

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api_node_01
      - api_node_02
      - api_node_03