services:
  api_node_01:
    build: .
    env_file:
      - docker.env
    depends_on:
      mongo_db:
        condition: service_started

  api_node_02:
    build: .
    env_file:
      - docker.env
    depends_on:
      mongo_db:
        condition: service_started

  api_node_03:
    build: .
    env_file:
      - docker.env
    depends_on:
      mongo_db:
        condition: service_started

  mongo_db:
    image: mongo:7.0.2
    volumes:
      - ./data/mongo:/data/db

  elasticsearch_node_01:
    image: elasticsearch:8.10.2
    healthcheck:
      interval: 5s
      retries: 80
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://elasticsearch_db:9200
    environment:
     - cluster.name=docker-cluster
     - node.name=elasticsearch_node_01
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - discovery.seed_hosts=elasticsearch_node_02,elasticsearch_node_03
     - cluster.initial_master_nodes=elasticsearch_node_01,elasticsearch_node_02,elasticsearch_node_03
     - xpack.security.enabled=false
     - http.cors.enabled=true
    volumes:
      - ./data/elasticsearch_01:/usr/share/elasticsearch/data

  elasticsearch_node_02:
    image: elasticsearch:8.10.2
    environment:
     - cluster.name=docker-cluster
     - node.name=elasticsearch_node_02
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - discovery.seed_hosts=elasticsearch_node_01,elasticsearch_node_03
     - cluster.initial_master_nodes=elasticsearch_node_01,elasticsearch_node_02,elasticsearch_node_03
     - xpack.security.enabled=false
     - http.cors.enabled=true
    volumes:
      - ./data/elasticsearch_02:/usr/share/elasticsearch/data

  elasticsearch_node_03:
    image: elasticsearch:8.10.2
    environment:
     - cluster.name=docker-cluster
     - node.name=elasticsearch_node_03
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - discovery.seed_hosts=elasticsearch_node_01,elasticsearch_node_02
     - cluster.initial_master_nodes=elasticsearch_node_01,elasticsearch_node_02,elasticsearch_node_03
     - xpack.security.enabled=false
     - http.cors.enabled=true
    volumes:
      - ./data/elasticsearch_03:/usr/share/elasticsearch/data

  memcached_node_01:
    image: memcached

  memcached_node_02:
    image: memcached

  memcached_node_03:
    image: memcached

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api_node_01
      - api_node_02
      - api_node_03