services:
  api:
    build: .
    ports:
      - 8000:8000
    environment:
      - MONGO_URI=mongodb://mongo:27017

  database:
    image: mongo
    container_name: mongo
    volumes:
      - ./data:/data/db