x-mongodb-healthcheck: &mongodb-healhcheck
  healthcheck:
    test: echo 'db.runCommand("ping").ok' | mongosh 127.0.0.1:27017/test --quiet
    interval: 10s
    timeout: 10s
    retries: 5
    start_period: 40s

services:

  mongo_db_node_01:
    image: mongo:7.0.2
    <<: [ *mongodb-healhcheck ]
    volumes:
      - ./data/mongo_node_01:/data/db
    command: mongod --replSet docker-replicaset
    ports:
      - 27017:27017

  mongo_db_node_02:
    image: mongo:7.0.2
    <<: [ *mongodb-healhcheck ]
    volumes:
      - ./data/mongo_node_02:/data/db
    command: mongod --replSet docker-replicaset
    ports:
      - 27018:27017

  mongo_db_node_03:
    image: mongo:7.0.2
    <<: [ *mongodb-healhcheck ]
    volumes:
      - ./data/mongo_node_03:/data/db
    command: mongod --replSet docker-replicaset
    ports:
      - 27019:27017

  mongo_cluster_init:
    image: mongo:7.0.2
    depends_on:
      mongo_db_node_01:
        condition: service_healthy
      mongo_db_node_02:
        condition: service_healthy
      mongo_db_node_03:
        condition: service_healthy
    volumes:
      - ./infrastructure/init-mongo.js:/scripts/init-mongo.js:ro
    entrypoint: [ "mongosh", "--host", "host.docker.internal", "--port", "27017", "--file", "/scripts/init-mongo.js"]