services:
  api:
    build: .
    ports:
      - 8000:8000
    environment:
      - MONGO_URI=mongodb://mongo_db:27017
      - ELASTICSEARCH_URI=http://elasticsearch_db:9200

  mongo_db:
    image: mongo:7.0.2
    volumes:
      - ./data/mongo:/data/db

  elasticsearch_db:
    image: elasticsearch:8.10.2
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node